#!/usr/bin/env ruby

require 'rubygems'
require 'getopt/std'
require 'yaml'
require 'zabbixapi'

opt = Getopt::Std.getopts("g:E:h:p:")

group_name = opt["g"]
zabbix_env = opt["E"]
host = opt["h"]
port = opt["p"]

template_name = "TMPL_Remote_#{host}_port_#{port}_availability"

# read config
config = YAML::load(open('./config.yml'))

api_url = config[zabbix_env]["api_url"]
api_login = config[zabbix_env]["api_login"]
api_password = config[zabbix_env]["api_password"]


# Esablish new connection
zbx = Zabbix::ZabbixApi.new(api_url, api_login, api_password)

# Create new template
p " * Creating template #{template_name}."
g_id = zbx.add_or_get_group(group_name)

options = {
  'groups' => [ g_id.to_i ],
  'host' => template_name
}

t_id = zbx.add_or_get_template(options)

# Create application #{app_name}
app_name = "Remote_#{host}_port_#{port}_availability"
p " ** Create application #{app_name}."
application = {
  'hostid' => t_id.to_i,
  'name' => app_name
}
a_id = zbx.add_or_get_application(t_id, application)

# 'Ping.'
options = {
  'description' => "Remote availability #{host} on port #{port}",
  'key_' => "net.tcp.port[#{host}, #{port}]",
  'hostid' => t_id.to_i,
  'applications' => [ a_id.to_i ],
  'history' => 7,
  'trends' => 30,
  'delay' => 30,
  'value_type' => 0,
  'type' => '0'
}
p " ** Add 'Remote_#{host}_port_#{port}_availability' to #{template_name}."
i_id = zbx.add_or_get_item(t_id, options)

# TRIGGERS
options = {
  'description' => "Remote availability #{host} on port #{port}",
  'expression' => "{#{template_name}:net.tcp.port[#{host}, #{port}].last(0)}#1",
  'priority' => 5, #disaster
  'templateid' => 0,
  'comments' => "Remote availability #{host} on port #{port}",
  'type' => 0,
  'status' => '0'
}

p " ** Add 'Remote availability #{host} on port #{port} disaster trigger'"
tr_id = zbx.add_or_get_trigger(t_id, options)
