#!/usr/bin/env ruby

require 'rubygems'
require 'yaml'
require 'getopt/std'
require 'zabbixapi'

opt = Getopt::Std.getopts("g:E:")

group_name = opt["g"]
zabbix_env = opt["E"]

template_name = "TMPL_Load_average"

# read config
config = YAML::load(open('./config.yml'))

api_url = config[zabbix_env]["api_url"]
api_login = config[zabbix_env]["api_login"]
api_password = config[zabbix_env]["api_password"]

# Esablish new connection
zbx = Zabbix::ZabbixApi.new(api_url, api_login, api_password)

# Create new template
p " * Creating template #{template_name}."
g_id = zbx.get_group_id(group_name)

options = {
  'groups' => [ g_id.to_i ],
  'host' => template_name
}

t_id = zbx.add_template(options)

# Create application #{app_name}
app_name = "Load_average"
p " ** Create application #{app_name}."
application = {
  'hostid' => t_id.to_i,
  'name' => app_name
}
a_id = zbx.add_application(application)

# 'Load Average 1'
options = {
  'description' => "Load Average 1",
  'key_' => "system.cpu.load[,avg1]",
  'hostid' => t_id.to_i,
  'applications' => [ a_id.to_i ],
  'history' => 7,
  'trends' => 30,
  'delay' => 60,
  'value_type' => 0
}
p " ** Add 'Load Average 1' to #{template_name}."

i_id = zbx.add_item(options)

# 'Load Average 5'
options = {
  'description' => "Load Average 5",
  'key_' => "system.cpu.load[,avg5]",
  'hostid' => t_id.to_i,
  'applications' => [ a_id.to_i ],
  'history' => 7,
  'trends' => 30,
  'delay' => 300,
  'value_type' => 0
}
p " ** Add 'Load Average 5' to #{template_name}."

i_id = zbx.add_item(options)

# TRIGGERS

options = {
  'description' => "Load Average",
  'expression' => "{#{template_name}:system.cpu.load[,avg5].last(0)}>5",
  'priority' => 2, # warning
  'templateid' => 0,
  'comments' => "Load Average (warning)",
  'type' => 0,
  'status' => '0'
}

p " ** Add 'Load Average warning trigger'"
tr_id = zbx.add_trigger(options)

options = {
  'description' => "Load Average",
  'expression' => "{#{template_name}:system.cpu.load[,avg5].last(0)}>10",
  'priority' => 5, # disaster
  'templateid' => 0,
  'comments' => "Load Average (disaster)",
  'type' => 0,
  'status' => '0'
}

p " ** Add 'Load Average disaster trigger'"
tr_id = zbx.add_trigger(options)
