#!/usr/bin/env ruby

require 'rubygems'
require 'getopt/std'
require 'yaml'
require 'zabbixapi'

opt = Getopt::Std.getopts("g:E:")

group_name = opt["g"]
zabbix_env = opt["E"]

template_name = "TMPL_cpufan_sensor"
app_name = "cpufan_sensor"
high_disaster_rpm = '5000'
low_disaster_rpm = '800'

# read config
config = YAML::load(open('./config.yml'))

api_url = config[zabbix_env]["api_url"]
api_login = config[zabbix_env]["api_login"]
api_password = config[zabbix_env]["api_password"]

# Esablish new connection
zbx = Zabbix::ZabbixApi.new(api_url, api_login, api_password)

# Create new template
p " * Creating template #{template_name}."
g_id = zbx.add_or_get_group(group_name)

options = {
  'groups' => [ g_id.to_i ],
  'host' => template_name
}

t_id = zbx.add_or_get_template(options)

# Create application #{app_name}
app_name = "cpufan_sensor"
p " ** Create application #{app_name}."
application = {
  'hostid' => t_id.to_i,
  'name' => app_name
}
a_id = zbx.add_or_get_application(t_id, application)

# 'cpu fan speed'
options = {
  'description' => "CPU FAN Speed sensor",
  'key_' => "cpufansensor",
  'hostid' => t_id.to_i,
  'applications' => [ a_id.to_i ],
  'history' => 7,
  'trends' => 30,
  'delay' => 60,
  'templateid' => t_id, 
  'value_type' => '3',
  'units' => 'rpm'
}
p " ** Add 'cpufansensor' to #{template_name}."
sensor_item_id = zbx.add_or_get_item(t_id, options)

# TRIGGER
# cpufan disaster (high threshold)
options = {
  'description' => "CPU FAN sensor high",
  'expression' => "{#{template_name}:cpufansensor.last(0)}>#{high_disaster_rpm}",
  'priority' => 5, # disaster
  'templateid' => 0,
  'comments' => "Cpufan sensor high threshold (Disaster)",
  'type' => 0,
  'status' => '0'
}
p " ** Add 'cpufan sensor high disaster' trigger"
zbx.debug = true
tr_id = zbx.add_or_get_trigger(t_id, options)

# TRIGGER
# cpufan disaster (high threshold)
options = {
  'description' => "CPU FAN sensor low",
  'expression' => "{#{template_name}:cpufansensor.last(0)}<#{low_disaster_rpm}",
  'priority' => 5, # disaster
  'templateid' => 0,
  'comments' => "Cpufan sensor low threshold (Disaster)",
  'type' => 0,
  'status' => '0'
}
p " ** Add 'cpufan sensor low disaster' trigger"
tr_id = zbx.add_or_get_trigger(t_id, options)

# GRAPH
options = {
  'gitems' => [
    {   
      "itemid" => sensor_item_id,
      "drawtype" => "0",
      "sortorder" => "0",
      "color" => "AA0000",
      "yaxisside" => "0",
      "calc_fnc" => "2",
      "type" => "0",
      "periods_cnt" => "5" 
    }
  ],  
  "show_triggers" => "1",
  "name" => "CPU FAN Speed sensor data from lm-sensors",
  "width" => "900",
  "height" => "200",
  "templateid" =>  "0" 
}

g_id = zbx.add_or_get_graph(t_id, options)
