#!/usr/bin/env ruby

require 'rubygems'
require 'yaml'
require 'getopt/std'
require 'zabbixapi'

opt = Getopt::Std.getopts("g:E:n:t:")

group_name = opt["g"]
zabbix_env = opt["E"]
disk_name = opt["n"]
parameter_name = opt["t"]

template_name = "TMPL_#{parameter_name}_#{disk_name}"

# read config
config = YAML::load(open('./config.yml'))

api_url = config[zabbix_env]["api_url"]
api_login = config[zabbix_env]["api_login"]
api_password = config[zabbix_env]["api_password"]

# Esablish new connection
zbx = Zabbix::ZabbixApi.new(api_url, api_login, api_password)

# Create new template
p " * Creating template #{template_name}."
g_id = zbx.add_or_get_group(group_name)

options = {
  'groups' => [ g_id.to_i ],
  'host' => template_name
}

t_id = zbx.add_or_get_template(options)

# Create application #{app_name}
app_name = "#{parameter_name}_#{disk_name}"
p " ** Create application #{app_name}."
application = {
  'hostid' => t_id.to_i,
  'name' => app_name
}
a_id = zbx.add_or_get_application(t_id, application)

# '#{parameter_name} for #{disk_name}'
options = {
  'description' => "#{parameter_name} for #{disk_name}",
  'key_' => "smart.state[#{disk_name},#{parameter_name}]",
  'hostid' => t_id.to_i,
  'applications' => [ a_id.to_i ],
  'history' => 7,
  'trends' => 30,
  'delay' => 60,
  'value_type' => 0
}
p " ** Add '#{parameter_name} for #{disk_name}' to #{template_name}."
param_id = zbx.add_or_get_item(t_id, options)

# TRIGGERS
options = {
  'description' => "Change of #{parameter_name} on #{disk_name} is too big",
  'expression' => "{#{template_name}:smart.state[#{disk_name},#{parameter_name}].abschange(0)}>10",
  'priority' => 2, # warning
  'templateid' => 0,
  'comments' => "too many reads on #{disk_name} (warning)",
  'type' => 0,
  'status' => '0'
}
p " ** Add '#{parameter_name} on #{disk_name}' trigger'"
tr_id = zbx.add_or_get_trigger(t_id, options)

# GRAPHS
options = {
  'gitems' => [
      "itemid" => param_id,
      "drawtype" => "0",
      "sortorder" => "0",
      "color" => "AA0000",
      "yaxisside" => "0",
      "calc_fnc" => "2",
      "type" => "0",
      "periods_cnt" => "5" 
  ],
  "show_triggers" => "1",
  "name" => "#{parameter_name} graph",
  "width" => "900",
  "height" => "200",
  "templateid" =>  "0" 
}

p " ** Add '#{parameter_name} graph'"
g_id = zbx.add_or_get_graph(t_id, options)
