#!/usr/bin/env ruby

require 'rubygems'
require 'getopt/std'
require 'yaml'
require 'zabbixapi'

opt = Getopt::Std.getopts("g:E:")

group_name = opt["g"]
zabbix_env = opt["E"]

template_name = "TMPL_nv_gputemp_sensor"
app_name = "nv_gputemp_sensor"
high_temperature = '70'
crit_temperature = '80'

# read config
config = YAML::load(open('./config.yml'))

api_url = config[zabbix_env]["api_url"]
api_login = config[zabbix_env]["api_login"]
api_password = config[zabbix_env]["api_password"]

# Esablish new connection
zbx = Zabbix::ZabbixApi.new(api_url, api_login, api_password)

# Create new template
p " * Creating template #{template_name}."
g_id = zbx.add_or_get_group(group_name)

options = {
  'groups' => [ g_id.to_i ],
  'host' => template_name
}

t_id = zbx.add_or_get_template(options)

# Create application #{app_name}
p " ** Create application #{app_name}."
application = {
  'hostid' => t_id.to_i,
  'name' => app_name
}
a_id = zbx.add_or_get_application(t_id, application)

# 'cpu temperature sensor'
options = {
  'description' => "Nvidia GPU Temperature sensor",
  'key_' => "nv-gputemp",
  'hostid' => t_id.to_i,
  'applications' => [ a_id.to_i ],
  'history' => 7,
  'trends' => 30,
  'delay' => 60,
  'value_type' => '3',
  'units' => 'C'
}
p " ** Add 'nv-gputemp' to #{template_name}."
sensor_item_id = zbx.add_or_get_item(t_id, options)

# TRIGGER
# nv-gputemp disaster (high threshold)
options = {
  'description' => "Nvidia GPU Temperature sensor warning",
  'expression' => "{#{template_name}:nv-gputemp.last(0)}>#{high_temperature}",
  'priority' => 2, # warning
  'templateid' => 0,
  'comments' => "Nvidia GPU temperature sensor (Warning)",
  'type' => 0,
  'status' => '0'
}
p " ** Add 'nv-gputemp sensor warning' trigger"
tr_id = zbx.add_or_get_trigger(t_id, options)

# TRIGGER
# cputemp disaster (high threshold)
options = {
  'description' => "Nvidia GPU temperature sensor disaster",
  'expression' => "{#{template_name}:nv-gputemp.last(0)}>#{crit_temperature}",
  'priority' => 5, # disaster
  'templateid' => 0,
  'comments' => "Nvidia GPU temperature sensor (Disaster)",
  'type' => 0,
  'status' => '0'
}
p " ** Add 'cputemp sensor disaster' trigger"
tr_id = zbx.add_or_get_trigger(t_id, options)

# GRAPH
options = {
  'gitems' => [
    {   
      "itemid" => sensor_item_id,
      "drawtype" => "0",
      "sortorder" => "0",
      "color" => "AA0000",
      "yaxisside" => "0",
      "calc_fnc" => "2",
      "type" => "0",
      "periods_cnt" => "5" 
    }
  ],  
  "show_triggers" => "1",
  "name" => "Nvidia GPU Temperature from nvidia-smi",
  "width" => "900",
  "height" => "200",
  "templateid" =>  "0" 
}

g_id = zbx.add_or_get_graph(t_id, options)
