#!/usr/bin/env ruby

require 'rubygems'
require 'getopt/std'
require 'yaml'
require 'zabbixapi'

opt = Getopt::Std.getopts("g:E:s:")

group_name = opt["g"]
zabbix_env = opt["E"]
stream = opt["s"]

template_name = "TMPL_mpeg2lander_#{stream}"
uri = "http://127.0.0.1:5000/api/lander_spec"

# read config
config = YAML::load(open('./config.yml'))

api_url = config[zabbix_env]["api_url"]
api_login = config[zabbix_env]["api_login"]
api_password = config[zabbix_env]["api_password"]

# Esablish new connection
zbx = Zabbix::ZabbixApi.new(api_url, api_login, api_password)

# Create new template
p " * Creating template #{template_name}."
g_id = zbx.add_or_get_group(group_name)

options = {
  'groups' => [ g_id.to_i ],
  'host' => template_name
}

t_id = zbx.add_or_get_template(options)

# Create application #{app_name}
app_name = "mpeg2lander_#{stream}"
p " ** Create application #{app_name}."
application = {
  'hostid' => t_id.to_i,
  'name' => app_name
}
a_id = zbx.add_or_get_application(t_id, application)

# 'mpeg2lander signal quality'
options = {
  'description' => "mpeg2lander #{stream} signal quality",
  'key_' => "mpeg2lander.signal[#{uri},#{stream}]",
  'hostid' => t_id.to_i,
  'applications' => [ a_id.to_i ],
  'history' => 7,
  'trends' => 30,
  'delay' => 60,
  'value_type' => 0
}
p " ** Add 'mpeg2lander #{stream} signal quality' to #{template_name}."
signal_item_id = zbx.add_or_get_item(t_id, options)

# TRIGGERS
# signal quality warning
options = {
  'description' => "mpeg2lander #{stream} low signal",
  'expression' => "{#{template_name}:mpeg2lander.signal[#{uri},#{stream}].last(0)}<81",
  'priority' => 2, # warning
  'templateid' => 0,
  'comments' => "Mpeg2lander #{stream} low signal (Warning)",
  'type' => 0,
  'status' => '0'
}
p " ** Add 'mpeg2lander signal warning' trigger"
tr_id = zbx.add_or_get_trigger(t_id, options)

# signal quality disaster
options = {
  'description' => "mpeg2lander #{stream} low signal",
  'expression' => "{#{template_name}:mpeg2lander.signal[#{uri},#{stream}].last(0)}<71",
  'priority' => 5, # disaster
  'templateid' => 0,
  'comments' => "Mpeg2lander #{stream} low signal (disaster)",
  'type' => 0,
  'status' => '0'
}
p " ** Add 'mpeg2lander signal disaster' trigger"
tr_id = zbx.add_or_get_trigger(t_id, options)


# GRAPH
options = {
  'gitems' => [
    {   
      "itemid" => signal_item_id,
      "drawtype" => "0",
      "sortorder" => "0",
      "color" => "AA0000",
      "yaxisside" => "0",
      "calc_fnc" => "2",
      "type" => "0",
      "periods_cnt" => "5" 
    }
  ],  
  "show_triggers" => "1",
  "name" => "Mpeg2lander #{stream} signal quality",
  "width" => "900",
  "height" => "200",
  "templateid" =>  "0" 
}

g_id = zbx.add_or_get_graph(t_id, options)
