#!/usr/bin/env ruby

require 'rubygems'
require 'getopt/std'
require 'yaml'
require 'zabbixapi'

opt = Getopt::Std.getopts("g:i:E:")

group_name = opt["g"]
zabbix_env = opt["E"]

template_name = "TMPL_ipmi"
app_name = "ipmi"

# read config
config = YAML::load(open('./config.yml'))

api_url = config[zabbix_env]["api_url"]
api_login = config[zabbix_env]["api_login"]
api_password = config[zabbix_env]["api_password"]

# Esablish new connection
zbx = Zabbix::ZabbixApi.new(api_url, api_login, api_password)

store = Hash.new()

# Create new template
p " * Creating template #{template_name}."
g_id = zbx.add_or_get_group(group_name)

options = {
  'groups' => [ g_id.to_i ],
  'host' => template_name
}

t_id = zbx.add_or_get_template(options)

# Create application #{app_name}
p " ** Create application #{app_name}."
application = {
  'hostid' => t_id.to_i,
  'name' => app_name
}
a_id = zbx.add_or_get_application(t_id, application)

# 'System temp'
options = {
  'description' => "sys-temp",
  'key_' => "ipmi.sys-temp",
  'hostid' => t_id.to_i,
  'applications' => [ a_id.to_i ],
  'history' => 7,
  'trends' => 30,
  'delay' => 60,
  'value_type' => 0
}
p " ** Add 'System temp' to #{template_name}."
item_id = zbx.add_or_get_item(t_id, options)

store["sys-temp"] = item_id

# TRIGGERS
options = {
  'description' => "System temp",
  'expression' => "{#{template_name}:ipmi.sys-temp.last(0)}>55",
  'priority' => 5, # disaster
  'templateid' => 0,
  'comments' => "System temp (disaster)",
  'type' => 0,
  'status' => '0'
}

p " ** Add 'System temp status' trigger"
tr_id = zbx.add_or_get_trigger(t_id, options)

options = {
  'description' => "System temp",
  'expression' => "{#{template_name}:ipmi.sys-temp.last(0)}>50",
  'priority' => 3, # warning
  'templateid' => 0,
  'comments' => "System temp (warning)",
  'type' => 0,
  'status' => '0'
}

p " ** Add 'System temp status' trigger"
tr_id = zbx.add_or_get_trigger(t_id, options)

# GRAPHS
options = {
  'gitems' => [
    {   
      "itemid" => store["sys-temp"],
      "drawtype" => "0",
      "sortorder" => "0",
      "color" => "009900",
      "yaxisside" => "0",
      "calc_fnc" => "2",
      "type" => "0",
      "periods_cnt" => "5" 
    }  
  ],  
  "show_triggers" => "1",
  "name" => "System temp",
  "width" => "900",
  "height" => "200",
  "templateid" =>  "0" 
}
g_id = zbx.add_or_get_graph(t_id, options)
